version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: csharp-chat-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - chat-network
    command: --default-authentication-plugin=mysql_native_password

  # Opcional: phpMyAdmin para administrar la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: csharp-chat-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: chatuser
      PMA_PASSWORD: chatpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - chat-network

volumes:
  mysql_data:

networks:
  chat-network:
    driver: bridge
